esp-rs/espflash

espflash/Cargo.toml, espflash/README.md, espflash/src/flasher.rs
=> add flashing progressbar

espflash/src/elf.rs
While esp8266, esp32 and esp32c3 seem to work fine with the "almost the same data" in the segments so far, esp32s2 bootloader seems to be a bit more picky (or maybe the linker script differences?)
=> use elf sections instead of elf segments for flashing

espflash/src/connection.rs, espflash/src/error.rs, espflash/src/flash_target/esp32.rs, espflash/src/flash_target/mod.rs, espflash/src/flasher.rs
And mention the command which timed out in the error message
=> fix erease timeout not being used for compressed flashing

README.md, cargo-espflash/README.md, espflash/README.md
Our READMEs were getting a little outdated in some places, so I just went ahead and revamped all of them. I believe I have included all the information which was previously in them, as well as added a few more points.
Please let me know if there are any issues or anything else you'd like to see added.
[README.md](https://github.com/jessebraham/espflash/blob/docs/readme-updates/README.md)  
[cargo-espflash/README.md](https://github.com/jessebraham/espflash/blob/docs/readme-updates/cargo-espflash/README.md)  
[espflash/README.md](https://github.com/jessebraham/espflash/blob/docs/readme-updates/espflash/README.md)
=> Update all READMEs, add missing information

espflash/src/partition_table.rs
=> Support multiple storage partitions and empty partition offsets

espflash/src/cli/monitor.rs
Fixes #128
@MabezDev can you please confirm (I have only tested on macOS, but was originally able to reproduce the error).
=> Add a check to the monitor for interrupted system calls

.github/workflows/package.yml, .github/workflows/release.yml
=> Build release artifacts for additional targets

cargo-espflash/src/main.rs
=> Pass-through --target-dir to cargo

espflash/src/image_format/esp32bootloader.rs
Fixes the issue described in #225
This took way too long to figure out, but currently `espflash` appends a workaround padding without actually increasing the segment size - this causes the following segments to become corrupted (as their header is moved back and 0s are inserted).
See original python code for reference (this PR makes the Rust code correctly resemble the python code):
https://github.com/espressif/esptool/blob/b37496f86ddd74a850533401067fd5054a746824/esptool/bin_image.py#L738-L748
Closes #225
=> Fix workaround causing corruption of segment length

espflash/src/flasher/mod.rs
=> Fix `FlashSize` discrepancy between `clap`, `strum` and `FromStr`

.github/workflows/package.yml, .github/workflows/raspberry_package.yml, .github/workflows/raspberry_rust.yml, .github/workflows/rust.yml
- Update `mad9000/actions-find-and-replace-string `
- Bump `actions/checkout`
- Bump `Swatinem/rust-cache`
- Replace `actions-rs/toolchain` by `dtolnay/rust-toolchain`
- Avoid using `actions-rs/cargo`
=> Fix CI warnings

.github/workflows/raspberry_rust.yml, .github/workflows/rust.yml, Cargo.lock, cargo-espflash/Cargo.toml, cargo-espflash/README.md, espflash/Cargo.toml, espflash/README.md, espflash/src/cli/serial.rs
Closes #365
Additionally bumps the MSRV due to new dependencies requiring such.
=> Restore the cursor when exiting from serial port selection via Ctrl-C

espflash/src/error.rs
See https://github.com/esp-rs/espflash/pull/397#discussion_r1184959133
=> Reword elf too big error

.github/workflows/rust.yml, CHANGELOG.md
- Add changelog
- Add CI check to enforce changelog modifications
=> Add CHANGELOG

.github/workflows/ci.yml
This should avoid needing to apply fixes like #420 in the future.
=> Additionally check the `x86_64-unknown-linux-musl` target in CI

CHANGELOG.md, Cargo.lock, README.md, cargo-espflash/Cargo.toml, cargo-espflash/README.md, espflash/Cargo.toml, espflash/README.md, espflash/src/cli/config.rs
=> Version 2.0.0-rc.4

CHANGELOG.md, espflash/src/cli/monitor/mod.rs
=> Delay processing of incomplete UTF-8 sequences

espflash/src/flasher/mod.rs
This makes flashing a bit faster vs calling `write_bin_to_flash` because it
does the "spi attach" only once.
=> flasher: add write_bins_to_flash.

CHANGELOG.md, espflash/src/cli/monitor/mod.rs, espflash/src/cli/monitor/parser/esp_defmt.rs, espflash/src/cli/monitor/parser/mod.rs, espflash/src/cli/monitor/parser/serial.rs
Fixes #502
cc https://github.com/esp-rs/espflash/pull/493#discussion_r1390694672
=> Fix defmt losing bytes

CHANGELOG.md, Cargo.lock, cargo-espflash/src/main.rs, espflash/Cargo.toml, espflash/src/bin/espflash.rs, espflash/src/cli/mod.rs, espflash/src/error.rs, espflash/src/flasher/mod.rs, espflash/src/targets/flash_target/esp32.rs, espflash/src/targets/mod.rs
Implements verify, closes #259 
Implements skip flashing of unchanged flash regions, closes #479
=> Implement skip and verify

espflash/src/targets/esp32p4.rs
=> Fix accidentally introduced build errors

espflash/Cargo.toml
Fix the bin's required features
=> Fix required features

.github/workflows/ci.yml
This PR exposes the compile error I'm seeing in #563
=> Actually check the lib in CI

CHANGELOG.md, README.md
The GH workflow badge was just the raw image, clicking it loaded that image in a new tab.
=> Link GH workflow & Crates.io badges

.github/workflows/ci.yml, .github/workflows/hil.yml
Also configure the repository to use merge queue. Once this PR is merged, I'll update the list of required checks for the PR to be merged in the settings.
=> Update the conditions that trigger the CI workflows

espflash/src/connection/mod.rs
I think this makes all commands easier to debug
=> Use hex fmt for command debug print

CHANGELOG.md, espflash/src/bin/espflash.rs, espflash/src/cli/mod.rs, espflash/src/command.rs, espflash/src/connection/mod.rs, espflash/src/error.rs, espflash/src/flasher/mod.rs, espflash/tests/scripts/board-info.sh
Closes https://github.com/esp-rs/espflash/issues/704
I've tried to follow esptool's implementation and output formatting as close as possible here.
=> Add get-security-info command

CHANGELOG.md, espflash/src/cli/mod.rs, espflash/src/error.rs, espflash/tests/scripts/erase-region.sh
closes https://github.com/esp-rs/espflash/issues/753
=> erase-region: Check if the address and size is multiple of 4096 and add HIL test

cargo-espflash/README.md, espflash/README.md
closes https://github.com/esp-rs/espflash/issues/728
=> Mention WSL2 in READMEs

.github/workflows/hil.yml, CHANGELOG.md, espflash/src/cli/mod.rs, espflash/tests/scripts/save-image_write-bin.sh
closes https://github.com/esp-rs/espflash/issues/684
=> add `--monitor` option to `write-bin`

.github/workflows/hil.yml, CHANGELOG.md, espflash/src/connection/mod.rs, espflash/src/error.rs, espflash/src/flasher/mod.rs, espflash/tests/scripts/read-flash.sh
closes https://github.com/esp-rs/espflash/issues/787
=> Fix `read-flash` which didn't work with some lengths

.github/workflows/hil.yml, CHANGELOG.md, espflash/src/cli/mod.rs, espflash/src/connection/command.rs, espflash/src/flasher/mod.rs, espflash/tests/scripts/read-flash.sh
closes https://github.com/esp-rs/espflash/issues/757
=> Add `ROM` version of `read-flash` command

CHANGELOG.md, espflash/src/cli/mod.rs, espflash/src/cli/monitor/mod.rs, espflash/src/cli/monitor/symbols.rs, espflash/tests/data/README.md, espflash/tests/scripts/flash.sh
Companion PR for https://github.com/esp-rs/esp-hal/pull/3276
=> Detect log format metadata

.github/workflows/hil.yml, CHANGELOG.md, espflash/src/error.rs, espflash/src/flasher/mod.rs, espflash/src/targets/esp32.rs, espflash/src/targets/esp32c2.rs, espflash/src/targets/esp32c3.rs, espflash/src/targets/esp32c6.rs, espflash/src/targets/esp32h2.rs, espflash/src/targets/esp32p4.rs, espflash/src/targets/esp32s2.rs, espflash/src/targets/esp32s3.rs, espflash/src/targets/mod.rs, espflash/tests/scripts/flash.sh
Still needs more testing, so opening as draft for now; would like to see the HIL results. __EDIT:__ Seems I've broken something 😁 
Also am not in love with the current `TryFrom` implementation for `Chip`, as it's yet another place that needs updating when adding chip support, but it gets the job done at least. Maybe we can come up with something better, will sleep on it.
Closes #767
=> Add chip detection using security info

CHANGELOG.md, espflash/src/cli/mod.rs, espflash/src/flasher/mod.rs, espflash/src/image_format/esp_idf.rs, espflash/src/targets/esp32.rs, espflash/src/targets/esp32c2.rs, espflash/src/targets/esp32c3.rs, espflash/src/targets/esp32c6.rs, espflash/src/targets/esp32h2.rs, espflash/src/targets/esp32p4.rs, espflash/src/targets/esp32s2.rs, espflash/src/targets/esp32s3.rs, espflash/src/targets/mod.rs
=> Don't leak `object` crate's `ElfFile32` type in public APIs

espflash/src/image_format/esp_idf.rs
Sometimes there's a bit of space between segments. Closes #837
=> Fix segment merging

cargo-espflash/src/main.rs, espflash/src/bin/espflash.rs, espflash/src/cli/mod.rs, espflash/src/connection/mod.rs, espflash/src/connection/reset.rs, espflash/src/flasher/mod.rs
Slightly touched `flasher` module too for` C-CONV` to have more sense
=> Rust API guidelines: `connection` module
