esp-rs/espflash

- cargo-espflash/README.md
- cargo-espflash/src/main.rs
Cool project! Has been very useful in removing hacky scripts that invoke esptool.
This PR adds functionality to choose how to build the project, instead of just relying on xargo. I'm attempting to rewrite the xtensa-quickstart repo without needed any other tools to build the code. If it goes well I will be recommending this tool for sure :)
> Add `--tool` flag to specify how to build the crate before flashing.

- cargo-espflash/src/main.rs
- espflash/src/connection.rs
- espflash/src/flasher.rs
- espflash/src/main.rs
```
$ time cargo espflash --chip esp32 --example blinky --speed 115200 /dev/ttyUSB0
Finished dev [unoptimized + debuginfo] target(s) in 0.01s
cargo espflash --chip esp32 --example blinky --speed 115200 /dev/ttyUSB0  0.09s user 0.17s system 1% cpu 15.113 total
```
```
time cargo espflash --chip esp32 --example blinky --speed 921600 /dev/ttyUSB0
Finished dev [unoptimized + debuginfo] target(s) in 0.01s
WARN setting baud rate higher than 115200 can cause issues.
cargo espflash --chip esp32 --example blinky --speed 921600 /dev/ttyUSB0  0.09s user 0.17s system 6% cpu 4.181 total
```
15s -> 4s :tada:
> Initial support for increased flashing speeds for the ESP32

- cargo-espflash/src/main.rs
`cargo espflash --board-info <serial>` was failing when leaving out the chip id. Fixed it by reconfiguring the baud rate right after creating the serial connection (just like in espflash).
> reconfigure baud rate in cargo-espflash when creating the serial connection

- espflash/src/chip/mod.rs
ESP32 was using the target string for ESP8266 and vice versa.
> Correct chip target strings

- cargo-espflash/src/main.rs
* Remove hardcoded passing of build-std args
* Instead note that the `--tool cargo` requires configuration in
`.cargo/config{.toml}`
Closes #19
> Fix build std presumptions

- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/src/chip/mod.rs
- espflash/src/config.rs
* Default to always use build-std.
Closes #28
> Remove references to Xargo and cargo xbuild

- cargo-espflash/Cargo.toml
- cargo-espflash/src/cargo_config.rs
- cargo-espflash/src/main.rs
Builds on top of #29 
Based on the way `cargo flash` handles [building the project](https://github.com/probe-rs/probe-rs/blob/9bdf72209e42b02db4911d958f45d46fb227e434/probe-rs-cli-util/src/lib.rs#L79).
With these changes I can successfully flash both bare metal Xtensa/RiscV esp programs & std library ones, such as [`ivmarkov`](https://github.com/ivmarkov/rust-esp32-std-hello)'s
> Improve builder

- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- espflash/Cargo.toml
Just a few small things:
- update `repository` fields in both `Cargo.toml` files to point to organization
- remove any mention of build tools from the `cargo-espflash` README
- remove unused dependency from `cargo-espflash`
> Update repository URLs, remove build tool info from README

- espflash/src/chip/esp32/partition_table.rs
> actually use the correct partition table when saving

- espflash/src/flasher.rs
Some operations (like erasing or writing flash) will depend on the size being erased or written.  For larger sizes (e.g 1MB), 3 seconds is often not enough.
Timeouts taken from esptool.py (https://github.com/espressif/esptool/blob/1db7a236c5ad5ed989ba6df0d9e0eabe060a0357/esptool.py#L77-L87).
> Use variable timeouts for different flash operations

- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/chip/mod.rs
- espflash/src/flasher.rs
I've been wanting to do this for awhile and finally got around to it. While part of the reason was purely personal preference, this also (IMO) makes it easier for us to add options, performs better validation of command-line arguments, and doesn't require manual updates of the argument parsing function and help messages.
As a note, I did remove the `--chip` option as it was not actually being used (we perform auto-detection). I am fine with adding it back for compatibility reasons, but I personally don't see the need.
> Use clap instead of pico-args for cargo-espflash

- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/chip/esp32.rs
- espflash/src/chip/esp32c3.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/flasher.rs
- espflash/src/lib.rs
- espflash/src/main.rs
- espflash/src/partition_table.rs
Adds a `--partition-table` option to _cargo-espflash_ which, if provided, attempts to parse the CSV file at the given path and produce a usable `PartitionTable`. If this option is not provided then the default table is generated via `PartitionTable::basic` instead.
This was requested in #26.
> Add support for providing custom partition tables

- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/chip/esp32.rs
- espflash/src/chip/esp32c3.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/flasher.rs
- espflash/src/lib.rs
- espflash/src/main.rs
- espflash/src/partition_table.rs
This builds on #40.
Adds a `--bootloader` option to _cargo-espflash_ which, if provided, loads the bytes from the binary file at the given path and provides them to the `Flasher`. If this option is not provided then the default bootloader is included as before.
This was requested in #26.
> Add support for providing custom bootloaders

- cargo-espflash/Cargo.toml
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- espflash/src/main.rs
- espflash/src/partition_table.rs
uses [`miette`](https://github.com/zkat/miette) for error reporting and extends the error messages to hopefully be more useful for users.
Some examples:
> improved error messages

- .github/workflows/rust.yml
- cargo-espflash/Cargo.toml
- cargo-espflash/src/line_endings.rs
- cargo-espflash/src/main.rs
- cargo-espflash/src/monitor.rs
- espflash/src/connection.rs
- espflash/src/flasher.rs
Adds a basic `--monitor` option to open a serial monitor after flashing is completed
> Add basic serial monitor

- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- cargo-espflash/src/package_metadata.rs
Allow specifying the partition table and bootloader in the project configuration to save users from having to specify the command line options every time.
This currently has a hard requirement on the file extensions of partition table and bootloader files, to keep the option open to have different non-filename options for these fields in the future (maybe specifying a crate name for the bootloader or something)
> allow specifying partition table and bootloader in the projects Cargo.toml

- cargo-espflash/src/main.rs
- espflash/src/connection.rs
- espflash/src/main.rs
Having software flow control enabled causes `FlashDeflateBegin` to time out for some reason
> disable software flowcontrol for serial

- espflash/src/chip/esp32.rs
- espflash/src/chip/esp32c3.rs
- espflash/src/chip/esp32s2.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/elf.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/image_format/esp8266.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
for now it still only supports the default esp8266 and esp32 formats, but this paves the way for adding support for alternative formats later on
> split image formats into it's own modules

- Dockerfile
Hi,
This allow to let Docker know when it should update its git clone of esp-rs/rust, by using the Last-Modified HTTP header provided by Github,
It is not exact, but I find it a good compromise  between cache hit, speed, and rebuild triggering when there is anything new.
> (in)validate docker cache for rust-xtensa clone

- Dockerfile
to fix:
```
Building LLVM for x86_64-unknown-linux-gnu
[…]
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
Call Stack (most recent call first):
/usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.16/Modules/FindPython/Support.cmake:2214 (find_package_handle_standard_args)
/usr/share/cmake-3.16/Modules/FindPython3.cmake:300 (include)
CMakeLists.txt:700 (find_package)
```
since https://github.com/espressif/llvm-project/commit/5e31e226b5b2b682607a6578ff5adb33daf4fe39
> docker: switch to python 3

- cargo-espflash/src/cargo_config.rs
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- cargo-espflash/src/package_metadata.rs
- espflash/src/chip/esp32.rs
- espflash/src/chip/esp32c3.rs
- espflash/src/chip/esp32s2.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- proper error when `cargo espflash` is being ran outside a project directory
- better error message when `Cargo.toml`/`.cargo/config.toml` can't be parsed
- Error message when configured target for the project doesn't match the attached chip
- Error message when no target has been configured for the project
- Show which command failed when the bootloader returns an error
> More error improvements

- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/error.rs
- espflash/src/partition_table.rs
Adds various validation steps and error messages for partition tables
- Add error when partitions overlap
- Add error when two partitions have the same name or sub-type
- Add error when the type and sub-type don't match for a partition
(the "trough" -> "through" typo has been fixed after taking the screenshot)
- Better error message when an unknown sub-type is specified for a partition
- Add error when app partitions aren't aligned properly
> Partition table validation

- README.md
- cargo-espflash/README.md
- espflash/README.md
We have been lying to our users 😁 🙉
> Fix typo in supported chip name (S3 -> S2)

- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/image_format/esp8266.rs
This replicates the behaviour in `esptool.py`. Rather than terminate the flashing process, it's likely that using a sane default value will still work. If this flash size is not supported for the detected chip or the application image is too large an error should be generated regardless.
I have an ESP32-S3 development board whose flash ID is _not_ recognized, which was what prompted me to do this.
Additionally adds two flash sizes and IDs from `esptool.py` which were not present here.
> If flash size cannot be detected, print a warning and default to 4MB

- cargo-espflash/src/main.rs
- espflash/src/chip/esp32/esp32.rs
- espflash/src/chip/esp32/esp32c3.rs
- espflash/src/chip/esp32/esp32s2.rs
- espflash/src/chip/esp32/mod.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/connection.rs
- espflash/src/flasher.rs
- espflash/src/main.rs
As the title says, adds a way to read eFuse values. Various information such as silicon revision, MAC address, chip features, etc. are accessible via the eFuse memory.
This PR contains a small refactor of the `chip` module as well, just slightly better separation of concerns.
I have additionally moved the `board_info` function out of `cargo-espflash` into the `Flasher` module, so that it can also be used by `espflash` without duplication.
Closes #39.
> Add a method of reading eFuse values

- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- espflash/src/chip/esp32/esp32.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/elf.rs
- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/image_format/esp8266.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
Allows saving the rom image instead of flashing it
- No attempt to connect to a device is made
- Image format is determined by matching against the configured target to auto detect the chip
- If an image contains multiple segments (esp8266) the output paths are prefixed by the address for the segment
Fixes #57
> add cargo-espflash subcommand to save the generated image to disk

- cargo-espflash/src/main.rs
- cargo-espflash/src/package_metadata.rs
- espflash/src/chip/esp32/esp32.rs
- espflash/src/chip/esp32/esp32c3.rs
- espflash/src/chip/esp32/esp32s2.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
- espflash/src/elf.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/image_format/esp32directboot.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
- espflash/src/main.rs
Fixes #53
Tested with https://github.com/MabezDev/esp32c3-experiments
Todo:
> add support for flashing direct-boot images to esp32c3

- cargo-espflash/src/main.rs
- espflash/src/cli/clap.rs
See title. Command-line argument takes priority over cargo config.
cc @georgik
> Allow for the build target to be specified via the command line as well

- cargo-espflash/src/main.rs
- espflash/src/chip/esp32/esp32.rs
- espflash/src/chip/esp32/esp32c3.rs
- espflash/src/chip/esp32/esp32s2.rs
- espflash/src/chip/esp32/esp32s3.rs
- espflash/src/chip/esp8266.rs
- espflash/src/chip/mod.rs
I made a pretty silly mistake in #88 in that I wasn't actually providing the target to cargo. This should fix that.
I also made the `supports_target` function more strict and changed it to use a default implementation. Using the `starts_with` method it is still possible to pass an invalid target value.
> Explicitly set build target to use --target value if provided

- .github/workflows/release.yml
- .github/workflows/rust.yml
- cargo-espflash/Cargo.toml
- espflash/Cargo.toml
- espflash/src/chip/mod.rs
- espflash/src/cli/clap.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor.rs
- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
Will eventually close #52.
Tested various chips and functionality on macOS, and minimal testing on Windows 10.
* The `serial` crate was swapped out with `serialport`
* `serial` has not received an update in ~4 years, `serialport` is somewhat maintained
* `serialport` was almost a drop-in replacement, and gives us the `available_ports` function as well
* Implements fairly basic port detection for `cargo espflash` and `espflash`
* If no port has been specified by CLI or config, attempts auto-detection
* If only one port is detected, it is selected automatically
* If multiple ports are detected, the user is prompted to select one
Presently I am only filtering serial ports by type, allowing USB ports only. Questions regarding this:
1) Is there any reason to support other port types (other …
> Serial port auto-detection

- espflash/src/connection.rs
- espflash/src/flasher.rs
~~This is built on top of #75, so I will convert it from a draft once that gets merged.~~
I believe this should resolve #18 and #90.
This PR emulates the connection logic performed by `esptool.py` and should help with connection issues on older devices. Essentially this adds two things:
1) Retry the connection until we connect to the device, or reach the attempt limit
2) Alternate between the default delay and a longer delay, which helps with older devices (eg. ESP32 rev 0)
> Retry failed connection attempts

- cargo-espflash/README.md
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- espflash/src/cli/clap.rs
Examples in a project (or just the project in general) might be organized as packages within a cargo workspace.
To make `cargo espflash` handle those scenarios, the `--package` option has to be supported and forwarded to the build step. If a binary crate was selected with the `--package` option, the build step will return the path to the generated binary in the shared `target` folder just like in the other scenarios. 
If a library crate was selected with `--package`, an error `cargo_espflash::no_artifact` will be issued. The help text for that error has been updated as part of the PR.
I've also updated the READMEs by just adding the option to the command help section, but since these sections are not in line with the code right now (see #94), I propose to rebase and properly document this …
> Add `--package` option

- espflash/src/main.rs
Small fix, but previously `espflash` was printing the help message when the serial port was omitted and no configuration file was present.
> Fix the logic handling missing serial port command-line argument

- espflash/src/error.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/partition_table.rs
We were always flashing to the default app offset previously, ignoring the value set in user-provided partition tables. We now verify that the `factory` partition is present (as it is required) and use its offset instead. In the case of the default partition table this will be the default app offset anyways.
> Fix bug where partition table offset is not used

- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
serial ports from these adapters are used by default when auto detecting serial port.
> add list of known serial adapters used on dev boards

- espflash/src/cli/serial.rs
serialport's autodetect doesn't provide any port information when using musl linux we can do some manual parsing of sysfs to get the relevant bits without udev.
This doesn't handle as many cases as udev proper (it doesn't give the product name for half of the devices in my testing) and probably has more things not covered but it's better than nothing :)
> add fallback serial detect when musl

- espflash/src/connection.rs
Speed up flashing by infinite %!
Resolves #113 
Flashing binary before:
```
WARN setting baud rate higher than 115200 can cause issues.
[00:00:07] ########################################      16/16      segment 0x1000
[00:00:00] ########################################       1/1       segment 0x8000
[00:06:01] ########################################     742/742     segment 0x30000
```
Flashing binary after:
```
WARN setting baud rate higher than 115200 can cause issues.
[00:00:00] ########################################      16/16      segment 0x1000
[00:00:00] ########################################       1/1       segment 0x8000
[00:00:25] ########################################     742/742     segment 0x30000
```
> Use buffered writer

- .github/workflows/rust.yml
- espflash/src/cli/serial.rs
Closes #120.
For whatever reason, we are no longer able to download the `libuv-dev` deb archive from Azure's mirror, so I've just changed the workflow to use the official Ubuntu archives instead. A little hacky and ugly, but it gets the job done.
> Restore CI to working order

- espflash/src/connection.rs
Normally I would like to avoid moving data from a `Vec` to a `VecDeque` and back again but at this point of time, we are only reading 10 bytes at a time and I wanted this PR to be small.
Hopefully this resolves #116
> Buffer reads

- Cargo.lock
- cargo-espflash/Cargo.toml
- espflash/Cargo.toml
- espflash/src/cli/monitor.rs
- Move off of the `clap` release candidate to the stable release
- Reset the serial port's baud to 115,200 prior to starting the serial monitor, allowing the use of `--speed` and `--monitor` together
> Update `clap` to stable version, reset baud when starting serial monitor

- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/connection.rs
- espflash/src/flasher.rs
Thanks to @JurajSadel for his work on this!
As stated in the title, this adds support for flashing via the ESP32-C3's USB Serial JTAG peripheral. This required performing a small refactor for `get_serial_port` to instead return a `SerialPortInfo` struct, as we needed access to the `PID` later on.
Has been tested on macOS x86_64 successfully. I will test it on Windows later today, and I believe @MabezDev will be able to test on an M1 Mac.
Closes #93.
> Allow for flashing via the USB Serial JTAG peripheral

- cargo-espflash/src/main.rs
- espflash/src/cli/clap.rs
* I'm working on an [example for `esp-idf-hal`](https://github.com/sirhcel/esp-idf-hal/blob/318233cb54d72bf3457e2e6eb89f52586d7a4747/examples/ledc-simple.rs) whose builds require to set [some unstable options](https://github.com/esp-rs/esp-idf-hal/blob/fb7d886522bdcb757cc6481dbf55b0b8edc228cf/.github/workflows/ci.yml#L32)
* I did not manage to pass these options as `rustflags` via `.cargo/config.toml` as adding them there made `rustc` fail
```
esp-idf-hal % export ESP_IDF_SDKCONFIG_DEFAULTS=$(pwd)/.github/configs/sdkconfig.defaults; cargo build --target riscv32imc-esp-espidf
error: failed to run `rustc` to learn about target-specific information
Caused by:
process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C default-linker-libraries -Zbuild-std=std,panic_abort …
```
> Allow passing unstable options to Cargo

- espflash/src/elf.rs
- espflash/src/image_format/esp32directboot.rs
This goes together with: https://github.com/MabezDev/esp32c3-experiments/pull/5
~~It just doesn't produce gaps between the segments.~~
Edit:
Turned out the code used the VMA addresses of the sections but it's needed to use the LMA
Some additional logging statements revealed this:
```
CodeSegment addr=42000000 len=8, new addr = 0
CodeSegment addr=42000008 len=b378, new addr = 8
CodeSegment addr=3c00b380 len=32d8, new addr = b380
CodeSegment addr=3fc80000 len=c, new addr = 80000
length = 524300
```
So, it added 478336 zero bytes before the _.data_ section
Now it looks like this
```
CodeSegment addr=0 len=8, new addr = 0
CodeSegment addr=8 len=b378, new addr = 8
CodeSegment addr=b380 len=32d8, new addr = b380
CodeSegment addr=e660 len=c, new addr = e660
length = 58988
```
Also, the final …
> Fix image creation for direct boot

- espflash/src/partition_table.rs
(This is for an upcoming PR adding support for flash encryption)
The `encrypted` flag should be a symbol, not an integer. See:  
https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/security/flash-encryption.html#encrypted-partition-flag
This adds the `Flags` type (of which there is currently only one, `encrypted`) and updates the relevant code. Also performed some simplification, cleanup, and formatting while I was in here.
> Correct the handling or partition table flags

- espflash/src/chip/esp32/esp32c3.rs
We're able to perform atomic emulation for the C3:  
https://github.com/esp-rs/riscv-atomic-emulation-trap
However trying to use the `riscv32imac-unknown-none-elf` target results in an error saying it's unsupported.
> Support the riscv32imac target, which can be used via atomic emulation

- espflash/src/main.rs
I messed this up in a previous refactor, my bad. Should work now but please confirm.
> Fix a logical error preventing the board-info subcommand from being invoked

- espflash/src/cli/serial.rs
- espflash/src/error.rs
Previously there was a single error variant for serial related problems, `NoSerial`, which did not necessarily describe the problem. This PR has re-worked the serial related error handling to hopefully better describe what went wrong. While I was at it I did some cleanup which (IMO) makes parts of this code a bit more readable/understandable.
Is this new approach adequate? Are there any other cases which may require an additional error variant?
> Re-work the serial error types to make the problem more clear

- .github/workflows/rust.yml
- cargo-espflash/src/main.rs
- espflash/src/chip/esp32/esp32.rs
- espflash/src/chip/esp8266.rs
- espflash/src/cli/mod.rs
- espflash/src/connection.rs
- espflash/src/elf.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/image_format/esp8266.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
- espflash/src/main.rs
This PR now updates the boot loader header _and_ the app image header only when a user supplies override via the `-s`, `-m` and `-f` flags. 
If no overrides are provided, the header is extracted from the esp-idf bootloader, and the same settings are used for the app header, by doing this we allow esp-idf SDKCONFIG settings to work seamlessly with espflash.
Closes https://github.com/esp-rs/espflash/issues/140
> Customize firmware image header

- espflash/src/cli/monitor.rs
> Apply a temporary fix to the serial monitor to make Ctrl-c work again

- espflash/src/chip/esp32/mod.rs
- espflash/src/flasher.rs
- espflash/src/image_format/esp32bootloader.rs
The pre-defined `app_sizes` for the various `Esp32Param` assume a flash size which is not necessarily correct, e.g. there are esp32-c3 chips with 2MB. 
This pull request removes the need to supply a custom partition-table for those chips.
> Scale the app partition based on flash size.

- cargo-espflash/src/main.rs
- espflash/src/cli/mod.rs
- espflash/src/main.rs
Feature: add the option for merging bootloader, partition-table and application binary into a single binary.
Closes #79 
Note: To get a chip revision, the connection is needed, for simplicity, the revision None is used.
> Feature: add subcommand for merging binaries

- cargo-espflash/src/main.rs
- espflash/src/cli/monitor.rs
- espflash/src/connection.rs
- espflash/src/flasher.rs
- espflash/src/main.rs
Small refactor of @bjoernQ's workaround in #153. 
Closes #153
> bugfix: fix reset sequence for usb-serial-jtag chips

- cargo-espflash/src/package_metadata.rs
This was accidentally broken (by me) in a previous refactor.
The fields for these paths were originally `String` but were changed to `PathBuf`. Unfortunately both types have an `ends_with` function (but they behave differently), so this was not caught by the compiler.
See https://github.com/esp-rs/espflash/issues/156 for further context.
> Correct path extension checks for cargo package metadata

- espflash/src/connection.rs
I have same issue, fixed by add a line in  espflash/src/connection.rs:93 add sleep 10ms.
In my MacBook Pro 12.3.1, It's test OK.
> fix bug #149

- cargo-espflash/src/main.rs
> Fix parsing for multiple features

- espflash/src/cli/mod.rs
I think the earlier way the merge option was implemented was a bit surprising to the user and entirely undocumented in that. It created a new file `_merged` instead of the actual given path name. I think if a user provides `--merge` with a `file`, that `file` being the merged file is the expected outcome.
This refactors the merge functionality while providing a clear separation in terms of code paths for merged and unmerged paths while being overall less complex and less code to maintain.
This also fixes #159.
> Refactor merge option a bit

- espflash/src/connection.rs
- espflash/src/flash_target/esp32.rs
When the chip is reset via the USB-SERIAL-JTAG not everything is fully reset, the RTC domain stays active. Therefore, if the RTC watchdog is enabled before being put into download mode it will trigger when flashing, hence resetting the board and interrupting flashing.
The reason it always works on Arduino is that the RTC watchdog is explicitly disabled very early on in the boot process which doesn't seem to be the case for normal esp-idf applications, and therefore Rust applications. 
Closes #154
> Hack to disable the rtc watchdog when connecting under the usb-serial-jtag

- .github/workflows/rust.yml
- Cargo.lock
- README.md
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/error.rs
- espflash/src/lib.rs
- espflash/src/main.rs
- espflash/src/partition_table.rs
Fixes #165 and fixes #163. It's quite pretty too:
This is quite a bit more than I bargained for but I think this makes sense as parsing of the binary stuff is also in esp-idf's `gen_esp32part.py` and that's Python so we can't have that!
I had to bump the MSRV to 1.58 but I hope that's ok.
> Add partition-table subcommand

- cargo-espflash/src/main.rs
These are easy to support but important to ensure reproducibility and as such are a must for production deployments of modern firmware. :)
> Add --locked and --frozen options

- espflash/src/cli/mod.rs
- espflash/src/flash_target/esp8266.rs
- espflash/src/flash_target/ram.rs
- espflash/src/flasher.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
I'm trying to use espflash as library and needed to open up espflash a lil bit :D. Is there any reason not to do this? 
Also snuck in a trait bound on `ImageFormat` to make `dyn ImageFormat` `Send`able across threads, happy to open another PR if that's more suitable!
Edit: If this seems like a reasonable idea lmk and I'll fix the clippy issues.
> Make all library modules public

- espflash/src/chip/mod.rs
esptool uses the chip name _without_ the hypen, e.g esp32c3 instead of esp32-c3. I see no reason not to do the same here, typing a hyphen is annoying :D.
> remove hyphen from chip string

- cargo-espflash/README.md
- espflash/README.md
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
Closes #166 
Note: It is not possible to flash `usb-serial-jtag` chips with `WSL2` because the reset also resets `serial-jtag-peripheral` which disconnects the chip from WSL2.
> bugfix: flash with wsl2

- cargo-espflash/src/main.rs
- espflash/src/cli/mod.rs
Closes #185 
When the `esp-idf-sys` package is built, we store the paths to the already-compiled `bootloader.bin` and `partition-table.bin` files. If no alternatives have been specified via either command-line arguments and/or Cargo package metadata, then these binaries will be used instead of the defaults included with `espflash`.
When users are _not_ building `esp-idf-sys`, (ie. bare-metal) then the behaviour does not change.
@MabezDev @bjoernQ @ivmarkov @n3xed will this cause any issues which I have not thought of?
> Detect the bootloader and partition table from ESP-IDF when able

- espflash/src/flash_target/esp32.rs
Closes [#126 ](https://github.com/esp-rs/espflash/issues/171)
Interestingly even though flashing now succeeds, the application doesn't seem to start - I'm not sure if this is just my devkit though.
> Include the base address of the RTC peripheral when disabling the RTC WDT

- espflash/src/cli/mod.rs
- espflash/src/flasher.rs
- espflash/src/main.rs
This subcommand adds support for writing a binary file at a specific address in flash.
> Add "write-bin-to-flash" subcommand

- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/mod.rs
> Allow hex or decimal addresses to be passed to the write bin subcommand

- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/README.md
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor.rs
- espflash/src/main.rs
Include `serial-monitor` subcommand in `cargo-espflash` and `espflash` to allow monitoring a serial monitor without flashing.
Closes #197
> Add `serial-monitor` subcommand 

- espflash/src/cli/mod.rs
- espflash/src/partition_table.rs
> Consistently support binary partition tables

- Cargo.lock
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/cli/mod.rs
- espflash/src/main.rs
Checks [crates.io](https://crates.io) for a new version at the time of invocation, and prints a message to the user if an update is available.
You can test locally by hard-coding in a version below `1.6.0`.
> Check if a new version if available upon invocation

- espflash/src/cli/serial.rs
- espflash/src/partition_table.rs
> bugfix: Don't use canonicalized strings on Windows

- espflash/src/connection.rs
- espflash/src/partition_table.rs
This change fixes how the sync responses are read. 8 responses with the SYNC op should be read in total. Without doing this it was occasionally possible to have a SYNC response bleed into subsequent response reads resulting in failures. This was notably seen in RegRead when reading the MAGIC value just after performing the initial connection and sync.
> Fix sync behavior

- espflash/src/error.rs
- espflash/src/image_format/esp32bootloader.rs
- espflash/src/partition_table.rs
Adds support for custom partition types and sub-types. Refer to the ESP-IDF partition table documentation for more information on these:  
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html
@ollpu would you be able to test out this PR and confirm it is working for you, please?
Closes #219
> Add support for custom partition types and sub-types

- espflash/src/flash_target/esp32.rs
When using the stub, the data sent in FlashDeflateData is not actually
written to flash until after the ack is sent by the stub. Waiting for
FlashDeflateEnd ensures that all data sent during with FlashDeflateData
has been fully written.
> Wait for FlashDeflateEnd ack

- cargo-espflash/src/main.rs
- espflash/src/cli/mod.rs
- espflash/src/main.rs
Currently `espflash` creates a 16MB image when specifying a flash size of 16MB. When mass producing devices a flash size of 16MB significantly slows down the flashing process without any benefit.
In order to not break backwards compatibility and expectations a new command line switch has been introduced `--skip-padding`, which reduces the image size to only what is really used.
> Allow skipping the padding for image files

- cargo-espflash/src/main.rs
A beginner in esp decided to build several slightly different binaries by placing the source codes in `src/bin` in the same project. The following error message is produced when the binary to flash is not specified:
```
Error: cargo_espflash::multiple_artifacts
× Failed to build project
╰─▶ Multiple build artifacts found
help: Please specify which artifact to flash using --bin
```
Running `cargo espflash --bin myapp1 /dev/ttyACM0` doesn't seem to solve it, though, with this message:
```
error: Found argument '--bin' which wasn't expected, or isn't valid in this context
If you tried to supply `--bin` as a value rather than a flag, use `-- --bin`
```
This commit adds the option `--bin` to build_options, which has worked in my case.
> Add option --bin for choosing one binary when there are more than one binaries

- .github/workflows/rpi.yml
- Cargo.lock
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor.rs
- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/flasher.rs
- espflash/src/interface.rs
- espflash/src/lib.rs
This PR is heavily in the draft state, especially because ~it requires a nightly compiler at its current state and~ it's currently untested.
Raspberry Pis don't have hardware support for DTR, so their internal UART peripherials can't direcly be used in espflash. This PR adds `rppal` to manage two user-configurable GPIOs as RTS/DTR. This requires some platform-specific code, for which I have introduced the `Interface` struct (name pending), and a cargo feature called `raspberry`.
Some follow up work:
- GPIO isn't available (used or doesn't exist)
- or if DTR is not set for `Unknown` serial ports (assuming internal peripherial is covered here)
~Implementation depends on `trait_upcasting` because of https://github.com/esp-rs/espflash/pull/234/files#diff-9b8216d416248667f4612fb114829cb89c5754c …
> Support using the built-in UART peripherials of a Raspberry Pi

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/mod.rs
Of course, almost immediately after reworking the CLI they had to publish a new major version on us 😁 `cargo_toml` published an update requiring changes as well, so I've updated it and any other dependencies with new versions.
Unfortunately in this new version of `clap` they've taken away the `possible_values` attribute, so I've had to add a simple macro to replace it. This is incredibly unfortunate, but also not the end of the world.
There were also some small issues with our existing structures for the CLI arguments, so I had to address those as well. The `--monitor-baud` arg should not have been added to `ConnectArgs` (this was my bad) so I moved it out. Addressed some visual stuff too, just lowercasing options, etc.
Closes #248
> Update to `clap@4.0.x`

- espflash/src/elf.rs
- espflash/src/image_format/direct_boot.rs
- espflash/src/image_format/esp8266.rs
- espflash/src/image_format/idf_bootloader.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
This is the third in my series of planned refactors, following #245 and #247. This should be it for now, I hope.
Nothing too crazy here:
- Renamed the image formats to be a bit more specific, paves the way for adding additional image formats in the future
- This is done in anticipation of eventually adding `mcuboot` support
- Moves a couple functions into the modules they belong in
> Refactor: rename image format modules to allow for future expansion

- .github/workflows/package.yml
- .github/workflows/raspberry.yml
- .github/workflows/raspberry_package.yml
- .github/workflows/raspberry_rust.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- Went back to the old approach of having two files for generating release packages: One for raspberry targets, and another for the rest of the targets.
- Added `raspberry_rust.yml` which is the equivalent of `rust.yml` but for raspberry targets (I removed `fmt` check as it does not change between targets AFAIK)
Closes #250
> Add `raspberry` feature checks in CI.

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- cargo-espflash/src/package_metadata.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/esp8266.rs
- espflash/src/targets/mod.rs
We previously had `ImageFormatId` and `ImageFormatType`, which was both confusing and unnecessary. `ImageFormatType` has been eliminated altogether. `ImageFormatId` is now called `ImageFormatKind`, and its variants are better named to allow for future expansion.
> Clean up the image format enums

- espflash/Cargo.toml
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/connection.rs
- espflash/src/elf.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
- espflash/src/targets/mod.rs
This is just a first-pass, still a lot of room for improvement. This, at the very least, ensures that the top-level documentation shows something useful, and that each module has at least _some_ description. A good number of types and functions have documentation, but again it can definitely be better.
You can build locally and see the feature gates by running:
```bash
$ cargo rustdoc --open -- --cfg docsrs
```
> Begin work on improving documentation

- README.md
- cargo-espflash/README.md
- espflash/README.md
Pretty self-explanatory.
I wanted to pull as much out of the repo-level `README` as possible, as you only ever see it looking at the repository on GitHub. The other two files are rendered on [crates.io](https://crates.io) so they contain all relevant information, with plenty of duplication between the two files as necessary.
Rendered views:
- [`cargo-espflash/README.md`](https://github.com/esp-rs/espflash/tree/d0402d964bf029ac1aa81a31b938eedd03de96df/cargo-espflash)
- [`espflash/README.md`](https://github.com/esp-rs/espflash/tree/d0402d964bf029ac1aa81a31b938eedd03de96df/espflash)
- [`README.md` ](https://github.com/esp-rs/espflash/blob/d0402d964bf029ac1aa81a31b938eedd03de96df/README.md)
Please let me know if you feel anything is missing, or if any formatting/wording/etc. can be improved.
> Re-write all the READMEs

- espflash/src/connection.rs
In [stub_flasher.c:319](https://github.com/espressif/esptool/blob/52278a9c695d9d4298bed00085947b8cb28b1539/flasher_stub/stub_flasher.c#L319) we can see that error is sent before status:
```c
SLIP_send_frame_data(error);
SLIP_send_frame_data(status);
SLIP_send_frame_delimiter();
```
This PR swap those two fields in the `CommandResponse` struct.
> connection: Swap error and status in CommandResponse

- espflash/src/cli/config.rs
- espflash/src/elf.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/mod.rs
- espflash/src/interface.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/esp8266.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/esp8266.rs
- espflash/src/targets/flash_target/mod.rs
- espflash/src/targets/flash_target/ram.rs
- espflash/src/targets/mod.rs
Still need to document all the public functions in all of the structs, though I'm not sure if I'll go that far before the release...
> Additional docstrings for `enums`, `structs`, and `traits`

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
Previously this subcommand only printed the application/partition sizes, which was sort of strange. It now prints some additional information in a similar way to the `board_info` function in `Flasher`.
Closes #264
> Print additional information when invoking the `save-image` subcommand

- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/targets/flash_target/esp32.rs
Since we just swapped the two fields, we need to check `error` instead of `status` now.
I've been mainly working with the stub since I'm erasing the OTA partition when flashing.
After taking a better look at the error handling there I'm not really sure where the values from `RomErrorKind` are coming from, since they are neither in the C stub code nor the `bootloader` and `bootloader_support` components.
I added the generic errors from the stub. There is other values used in other places in there but they are not under an enum and it would take quite a bit of time to reference all of them for now.
If anyone has any clue where those are coming from, otherwise I'd say that we can remove them at some point.
> connection: error handling

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/error.rs
Instead of having a `--erase-otadata` flag to erase only the otadata partition, we can now erase any partitions by their labels with `--erase-parts part1,part2`  or any data partition by their sub-types using `--erase-data-parts ota,nvs` and so on.
This PR is awaiting on https://github.com/esp-rs/esp-idf-part/pull/5
> Replace --erase-otadata with --erase-parts and --erase-data-parts

- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/esp8266.rs
- espflash/src/targets/flash_target/mod.rs
- espflash/src/targets/flash_target/ram.rs
Mostly just decoupling the progress bars from the flash targets in this. I think now all of the CLI-only dependencies are optional. Not 100% happy with it, but frankly it's good enough.
Closes #274
> Only display progress bars when `cli` feature is enabled, allow passing progress callback

- Cargo.lock
- espflash/Cargo.toml
This resolves an issue in which `deku` (used by `esp-idf-part`) had a dependency yanked, and as such we were unable to install without the `--locked` flag. Also presumably pulls in some additional improvements/fixes.
> Update dependencies to their latest versions

- espflash/src/cli/mod.rs
`--monitor` is an option I use very frequently.
What about adding a shortopt `-M` for convenience?
> Add shortopt -M for --monitor

- espflash/src/lib.rs
Functions like [`Connection::write_command`](https://docs.rs/espflash/1.7.0/espflash/connection/struct.Connection.html#method.write_command) are public, but the `Command` type, which is one of their argument, is not accessible outside of the crate. This PR makes the command module public so users have the opportunity to implement functionality other than flashing a binary.
> Make command module public

- espflash/src/cli/serial.rs
- espflash/src/connection.rs
This is just a small housekeeping PR to keep my fork free of warnings, as well as some cleanup/optimization I've noticed.
> Clean up unused code, optimize comparison in `find_serial_port`

- espflash/src/image_format/mod.rs
> Fix typo in `ImageFormatKind`'s `FromStr` implementation

- .github/workflows/raspberry_rust.yml
- .github/workflows/rust.yml
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- cargo-espflash/src/cargo_config.rs
- cargo-espflash/src/error.rs
- cargo-espflash/src/main.rs
- cargo-espflash/src/package_metadata.rs
- espflash/Cargo.toml
- espflash/README.md
Alright, let's try this again 😁 
I took the advice of @liebman and used `cargo` in place of the `cargo_toml` package, and this has resulted in a much more robust and flexible solution. Not entirely happy with the `load_metadata` function still, but it appears to work at least.
I did actually test this on hardware this time around, and it seems to be working as intended. @liebman if you could test this out one more time that would be appreciated!
Also cleaned up the errors module, bumped a couple dependencies, and some other little bits.
(Hopefully) closes #291
> Add support for using custom cargo metadata when in a workspace

- espflash/src/flasher/mod.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp8266.rs
Apparently there are variants of the ESP32-C2 with a 26MHz crystal instead of 40MHz. Due to a ROM bug, this needs special handling.
Additionally fixes the crystal frequency divider values for the ESP8266.
Closes #313
> Fix crystal frequency detection for ESP32-C2 and ESP8266

- espflash/Cargo.toml
- espflash/src/cli/mod.rs
This makes it possible to use `ESPFLASH_BAUD` env-variable to specify the flashing baud-rate.
This might be useful since the max possible baud-rate might be different depending on the host
> Support ESPFLASH_BAUD env var

- espflash/src/cli/serial.rs
> Reorder ports so that known ports appear first in CLI

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
This makes the functionality a bit more useful when using `espflash` as a library, and will also allow us to avoid multiple successive reads from the device during other operations.
> Make the flasher return a struct of device information instead of printing directly

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- fixes a bug introduced in 1a0a8481ff770ae3133d7d31634dcb95d9746fa9
- fixes the problem that flashing with `--monitor` didn't work for ESP32-C2 anymore
> Fix monitor after flash for ESP32-C2

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/command.rs
- espflash/src/flasher/mod.rs
- espflash/src/flasher/stubs.rs
- espflash/src/image_format/esp8266.rs
- espflash/src/image_format/idf_bootloader.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/mod.rs
- Update dependencies to their latest versions
- Derive `clap::ValueEnum` for all enums used as command line values, rather than the macro we were previously using
- Simplify the variant names of the flash configuration enums, making them more consistent in the process
- Fix a deprecation warning and a number of `clippy` warnings
> CLI improvements and dependency updates

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
This is what `esptool.py` does, so we will too!
Closes #336.
> Use the flasher stub by default

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/esp8266.rs
- espflash/src/targets/flash_target/mod.rs
- espflash/src/targets/flash_target/ram.rs
Hopefully this will make `espflash` a bit more usable as a library.
@bugadani does this seem reasonable enough to you? Would love to hear any feedback you might have.
I suppose this is sort of an extension of #283 as well, so @svenstaro will this still work for your use case as well? Sorry for changing this again 😁 
Closes #310.
> Add an optional callback trait which can be implemented and provided to most flashing functions

- .github/workflows/release.yml
This use to work, and now fails. It's not a super common target, and users can still install from source, so I'm not going to bother troubleshooting this right now.
Closes #312.
> No longer build releases for the Windows GNU target

- espflash/src/bin/espflash.rs
I was encountering this error while using the `espflash` CLI utility, more specifically the `write-bin` subcommand:
```
> cargo run -p espflash -- write-bin 0x0 file.bin
[2023-02-14T08:08:28Z INFO ] Serial port: 'COM20'
[2023-02-14T08:08:28Z INFO ] Connecting...
[2023-02-14T08:08:28Z INFO ] Serial port: 'COM20'
[2023-02-14T08:08:28Z INFO ] Connecting...
Error: espflash::connection_failed
x Failed to open serial port COM20
|-> Failed to open serial port COM20
|-> Error while connecting to device
`-> Serial port not found
help: Ensure that the device is connected and your host recognizes the serial adapter
```
And I found it strange that the serial port was being opened twice in a row, and by looking at the code I found the problem: `board_info` tries to open a new connection when a …
> Fix `espflash::write_bin`

- espflash/src/interface.rs
As it turns out, users (me) might actually want to construct `Interface` objects. While the fields are public, the raspberry-enabled `new` does a few useful things that I don't necessarily want to duplicate in my program.
> Make `Interface` constructor public

- espflash/src/error.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/flash_target/esp32.rs
Prior to this change, attempting to `espflash flash` with the `--format
direct-boot` argument targeting an esp32c3 would fail, reporting:
```
Error: espflash::unsupported_image_format
× Image format direct-boot is not supported by the esp32c3 revision v0.3
help: The esp32c3 only supports direct-boot starting with revision 3
```
However, direct-boot on this board was working prior to the changes in
https://github.com/esp-rs/espflash/commit/b25af06912e3c257261ac5ab9788217c0405d033, and looking at the [docs][esp32c3 revisions] it seems that the
mapping that was chosen for the `c3` specifically was `v0.REVISION`:
> ECO  | Revision (Major.Minor)
> ---------|-------------------
> ECO1 | v0.1
> ECO2 | v0.2
> ECO3 | v0.3
> ECO4 | v0.4
[esp32c3 revisions]: …
> fix: esp32c3 direct boot

- .gitignore
- cargo-espflash/src/main.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/flash_target/esp32.rs
> Disable watchdog timer before build.

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/error.rs
- espflash/Cargo.toml
- espflash/src/cli/config.rs
- New version of `toml` with some breaking API changes, which were addressed
- I forgot to gate `ctrlc` behind the `cli` feature when I added it
- #372
> Update `toml` dependency and fix errors, feature gate `ctrlc` dependency

- espflash/src/cli/serial.rs
Fixes #367.
Since I added the `matches` closure, it felt like some clean-up was appropriate. But if you'd prefer a more minimal PR I can do that too.
This also slightly changes the behavior of non-usb serial ports, for consistency. Previously, you could make them match by manually editing the config file and adding "vid=0, pid=0", but they wouldn't be sorted and highlighted as though they matched. After this change, non-usb serial ports won't auto-match at all.
> If exactly one port matches, use it

- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/config.rs
- Remove `serde-hex` since it's no longer compatible with the new `toml` version
- Include the `hex` crate
- Add functions for serializing and deserializing
- Add test for serialization and deserialization methods
Not sure if this is the best way, but the file needed to be backward compatible.
> Fix config file parsing

- espflash/src/image_format/idf_bootloader.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/mod.rs
I've implemented the third solution proposed by @maxwase in #375:
- Add `flash_freq` to `Esp32Params` so we can define a default flashing frequency per target.
- Specify the default flashing frequency for all the targets.
> Make the default flashing frequency target specific

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
Uses `clap_complete` to generate shell completions. Usage example:
```
espflash completions bash > /usr/share/bash-completion/completions/espflash.bash
```
**Note for `cargo-espflash` the completions have to be appended to the cargo completions**
These are the test that I did in my environment (using Linux and fish shell).
1. Install the crate from my branch:
```sh
cargo install espflash --git https://github.com/SergioGasquez/espflash --branch feature/shell-completions
```
2. Generate completions:
```sh
espflash completions fish > espflash.fish
```
3. Move the generated completions:
```sh
sudo mv espflash.fish /usr/share/fish/completions/espflash.fish
```
4. Here is the result of writing `espflash` and tabbing:
```sh
❯ espflash
board-info                    (Establish a connection with a …
```
> Generate Shell completions

- espflash/src/error.rs
> Add a diagnostic to tell the user about the partition table format 

- .github/workflows/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/ISSUE_TEMPLATE/config.yml
- .github/workflows/ISSUE_TEMPLATE/feature_request.md
I haven't been able to test it in my fork, but basically they are copied from https://github.com/esp-rs/espup/tree/main/.github/ISSUE_TEMPLATE where it works fine
> Add issue templates

- espflash/src/targets/mod.rs
Some chips can have more than 16MB of flash, mine has 32MB. Historically espflash failed to detect this flash size (and defaulted to 4MB) but now it can. Without this change, the board will boot loop because the esp idf bootloader max size is only 16MB.
Closes #393
> limit default partition size

- espflash/src/cli/serial.rs
@tingox would you mind verifying this fixes the issue for you, please?
Closes #409
> Fix handling of serial ports on BSD systems

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/flasher/mod.rs
Closes #396 (I think..?)
@dragazo @MabezDev please confirm this fixes the issue, but as far as I can tell we just were never passing the command-line argument to the `Flasher` struct when it was provided.
> Override the flash size in `Flasher` if provided via command-line argument

- cargo-espflash/src/error.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/connection.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/flasher/stubs.rs
- espflash/src/image_format/idf_bootloader.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/mod.rs
Additionally added some doc comments for types which were missing them.
> Fix a number of spelling errors in the documentation

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
I've kept these fairly minimal for the time being, with the expectation that we will expand on the help text as needed. With that said, would still like to get some feedback on what I have included.
> Add help text for all subcommands

- cargo-espflash/Cargo.toml
In #444, I reported that `cargo install` of cargo-espflash started failing for me this morning due to a build failure in the "cargo" dependency:
```
> cd cargo-espflash
> cargo install --path .
…
error[E0063]: missing field `rust_version` in initializer of `NewCrate`
--> /Users/myk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-0.71.0/src/cargo/ops/registry.rs:383:14
|
383 |             &NewCrate {
|              ^^^^^^^^ missing `rust_version`
For more information about this error, try `rustc --explain E0063`.
error: could not compile `cargo` (lib) due to previous error
error: failed to compile `cargo-espflash v2.0.1-dev (/Users/myk/Projects/espflash/cargo-espflash)`, intermediate artifacts can be found at `/Users/myk/Projects/espflash/target`
```
This branch fixes that …
> update 'cargo' dependency to 0.72

- .github/actions/setup-arm/action.yml
- espflash/Cargo.toml
- espflash/src/elf.rs
- espflash/src/targets/esp8266.rs
I investigated the CI failures and discovered it was a non-zero exit code from a call to `apt-get update` that was causing the workflow to fail.  In order to fix this, I had to fork the `gha-ubuntu-cross` repo and apply the fix there.  I'm working to get this fix upstreamed in https://github.com/cyberjunk/gha-ubuntu-cross/pull/6.  Once it is, we can revert this reference back to the original repo.
I also fixed a clippy warning that was added 1.72.0.  https://rust-lang.github.io/rust-clippy/master/index.html#/single_range_in_vec_init  The page says "this is almost always incorrect", but it seems clear that this is quite intentional in our case here.  So I silenced the warning by adding an `#[allow` annotation.
> Fix CI checks

- espflash/src/command.rs
~Draft PR until tested~
@georgik tested it and confirmed that the error is fixed with this branch
> Fix FlashDeflateData timeout error

- CHANGELOG.md
- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/esp_defmt.rs
- espflash/src/cli/monitor/parser/mod.rs
- espflash/src/cli/monitor/parser/serial.rs
Closes #316 
Counterpart of https://github.com/esp-rs/esp-println/pull/48 as it relies on the injected framing bytes. Not sure how to best lift this curse yet.
This PR adds a new compile-time `defmt` flag that enables defmt support in the binaries and the library. For this, the PR raises MSRV to 1.70. By default, the `defmt` feature is enabled. defmt detection is done by parsing the elf file.
The PR refactors serial port input handling so library users can define their own processing if they so choose. The default processor is able to recognize and parse frames generated by esp-println. Library users can disable this processing by using the `Serial` input processor or by disabling the `defmt` feature (which internally does the same besides disabling the dependencies).
> Print esp-println generated defmt messages

- cargo-espflash/Cargo.toml
This was missed when I undefaulted the feature
> Add defmt feature to cargo-espflash

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/mod.rs
~Add `-d/--defmt` flag for `monitor` and `flash` subcommands.~
Add `-f/--log-format` argument for `monitor` and `flash` subcommands.
cc @bugadani since you added this feature
~Draft until properly tested.~ Did some testing and seems to be working fine! 
We still need to figure out if we want opt-in or opt-out of defmt
> Add log-format argument

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
Adds an `--interactive` (or `-i`) flag that prevents auto-connection to a recognized device, even if it is the only recognized one.
> Add interactive flag

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- The flag `f` was already being used by [`flash-freq`](https://github.com/esp-rs/espflash/blob/39fbdacebaaa74a88e5d447a118f188be7d2e9bb/espflash/src/cli/mod.rs#L104), updated log-format to use `L`
- Since the PR was intended to be released in a minor version, we created `monitor_with` method to avoid changing `monitor`, now it can be modified
> Update log-format flag and merge monitor methods

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
When trying to build a C6 with and passing the `--chip esp32h2` arg: 
```
espflash/espflash on  feat/chip-arg [!?] is 📦 v3.0.0-dev via 🦀 v1.76.0-nightly took 7s 
❯ cargo r -r -- flash --monitor --chip esp32h2 esp32h2-app
Compiling espflash v3.0.0-dev (/home/sergio/Documents/Espressif/forks/espflash/espflash)
Finished release [optimized] target(s) in 6.84s
Running `/home/sergio/Documents/Espressif/forks/espflash/target/release/espflash flash --monitor --chip esp32h2 esp32h2`
[2023-11-20T14:16:55Z INFO ] Serial port: '/dev/ttyUSB0'
[2023-11-20T14:16:55Z INFO ] Connecting...
Error: espflash::chip_missmatch
× Chip provided (esp32h2) with `-c/--chip` does not match the detected chip (esp32c6)
help: Ensure that the correct chip is selected, or remove the `-c/--chip` option to autodetect the …
```
> Add `-c/--chip` argument

- espflash/src/cli/mod.rs
If we use `monitor --log-format defmt`  but don't provide the elf file, we won't be able to interpret the logs.
> Require --elf arg for --log-format arg in monitor subcommand

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/idf_bootloader.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/esp8266.rs
- espflash/src/targets/mod.rs
- Add a `--partition-table-offset` flag that corresponds to esp-idf's `CONFIG_PARTITION_TABLE_OFFSET`
- If the flag is specified, the partition table will be flashed to the given location.
- If the flag is omitted, the partition table location will be determined automatically from the partition table by subtracting 0x1000 from the first partition, which should be the most common case.
- The location of the application is now automatically determined from the partition table instead of the hard-coded 0x10000.
Closes #458
> Add handling for custom partition table offsets

- CHANGELOG.md
- espflash/src/connection/mod.rs
Dropping `BufWriter` flushes the internal buffers, but doesn't flush the inner stream. Calling `flush` directly does both _and_ also propagates any IO errors back to the caller.
May fix (or may not fix) issues like #450
> Flush buffer after writing command

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/esp_defmt.rs
- espflash/src/error.rs
> Don't silently fail if defmt data isn't available/correct

- espflash/src/flasher/mod.rs
We'd like to use this in probe-rs' flash size detection.
> Make `FlasherSize::from_detected` public

- cargo-espflash/src/main.rs
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/lib.rs
- Add warnings that `cli` mod does not provide SemVer guarantees
- Mark cli args as non_exhaustive
> Mark cli args as `non_exhaustive` and warn that `cli` mod doesnt provide SemVer guarantees.

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/idf_bootloader.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/esp8266.rs
- espflash/src/targets/mod.rs
With these changes, when using the argument and specifying a `--min-chip-rev ` greater that the chip revision you get:
```
Running `/home/sergio/Documents/Espressif/forks/espflash/target/release/espflash flash --min-chip-rev 5 esp32c3`
[2023-11-30T15:26:40Z INFO ] Serial port: '/dev/ttyACM0'
[2023-11-30T15:26:40Z INFO ] Connecting...
[2023-11-30T15:26:40Z INFO ] Using flash stub
[2023-11-30T15:26:40Z WARN ] Setting baud rate higher than 115,200 can cause issues
Error: espflash::unsupported_chip_revision
× Minimum supported revision is 5, connected device's revision is 3
```
> Add `min_chip_rev` argument

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/command.rs
- espflash/src/connection/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
This adds a `checksum-md5` command to espflash.
e.g.
```
❯ espflash checksum-md5 --address 0x10000 --length 0x1000 --no-stub
[2023-12-27T11:39:27Z INFO ] Serial port: 'COM22'
[2023-12-27T11:39:27Z INFO ] Connecting...
[2023-12-27T11:39:27Z WARN ] Setting baud rate higher than 115,200 can cause issues
0x95d0df6456de4ac114251a67a5f85
```
While this is not too exciting on its own, it's the ground work for #259 and #479
It's very unfortunate that the Rust flasher-stub currently doesn't implement the required command while the ROM code and the C based flasher stub does. (Verified by temporarily reverting the stubs locally). Maybe we should revert the change to use the Rust flasher-stub (but use it based on a feature at build time) until it's supported there
I checked the result with reading a …
> Add `checksum-md5` command

- cargo-espflash/README.md
- espflash/README.md
> Add defmt documentation

- CHANGELOG.md
- espflash/Cargo.toml
- espflash/src/error.rs
- espflash/src/lib.rs
This tries to avoid always pulling `libudev`, see #500. Not sure if it is the best approach, though.
> Add serialport feature

- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/lib.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32p4.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/esp8266.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/esp8266.rs
- espflash/src/targets/flash_target/mod.rs
- espflash/src/targets/flash_target/ram.rs
- espflash/src/targets/mod.rs
Featured gated `serialport` with more granularity.
Supersedes #555
> Fix lib compilation

- CHANGELOG.md
- espflash/src/flasher/mod.rs
This PR implements my suggestions from https://github.com/esp-rs/espflash/pull/512#issuecomment-1916650260 except for the error handling which is a more fundamental question it looks like.
> Add FlashDataBuilder

- CHANGELOG.md
- espflash/src/image_format/idf_bootloader.rs
Fixes #206 
We modify the ESP-IDF booloader's header - then we also need to re-calculate it's SHA256
> Re-calculate the bootloader's SHA256

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/command.rs
- espflash/src/connection/mod.rs
- espflash/src/connection/reset.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/flash_target/esp32.rs
- Adds the `-b/--before` argument
- Adds the `-a/--after` argument
This also solves #346 as `espflash monitor --before no-reset-no-sync --chip esp32c3` can monitor a target without resetting it.
> Add before and after reset arguments

- espflash/src/connection/mod.rs
- espflash/src/error.rs
In some (weird cases), like flashing a 26MHz C2 instead of 40Mhz target, https://github.com/esp-rs/espflash/issues/570 would happen. It should be an error, but the error should mean something, so I just added a custom error for the case.
> Add error for cases when we cant read the serial monitor trying to decode the bootmode

- CHANGELOG.md
- espflash/src/connection/mod.rs
My ESP32-WROOM is sending some non-utf8 data just after reset, causing boot mode detection to fail.
This commit uses `String::from_utf8_lossy` to ignore these bytes.
Tested on macOS, boards: ESP32-WROOM-32, ESP32-WROOM-32D, ESP32-C3-MINI-1, ESP32-C3-12F.
> Tolerate some non-utf8 data when detecting boot mode over serial

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- espflash/Cargo.toml
- espflash/README.md
- espflash/src/cli/monitor/mod.rs
- espflash/src/connection/reset.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/mod.rs
A number of dependencies were rather outdated, so they've all been brought up to date, and the required changes have been made. This required bumping the MSRV from `1.70` to `1.73` as well.
> Update dependencies and bump MSRV

- CHANGELOG.md
- espflash/src/cli/monitor/parser/mod.rs
- espflash/src/cli/monitor/symbols.rs
This turns this
```
Exception 'Illegal instruction' mepc=0x420001ba, mtval=0x0000a488
0x420001ba - embassy_hello_world::__run_task::{{closure}}
at C:\projects\esp\esp-hal\esp32c3-hal\examples\embassy_hello_world.rs:19
0x0000a488 - ??
at ??:??
TrapFrame
PC=0x420001ba         RA/x1=0x420001b2      SP/x2=0x3fc81778      GP/x3=0x3fccfee0      TP/x4=0x00000000
0x420001ba - embassy_hello_world::__run_task::{{closure}}
at C:\projects\esp\esp-hal\esp32c3-hal\examples\embassy_hello_world.rs:19
0x420001b2 - embassy_hello_world::__run_task::{{closure}}
at C:\projects\esp\esp-hal\esp32c3-hal\examples\embassy_hello_world.rs:19
0x3fc81778 - _ZN7esp_hal3rmt6asynch5WAKER17h7d00025adc6b0189E
at ??:??
0x3fccfee0 - _ZN7esp_hal3rmt6asynch5WAKER17h7d00025adc6b0189E
at ??:??
0x00000000 - core::num::<impl …
```
> Improve resolving symbols

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- espflash/Cargo.toml
- espflash/README.md
- espflash/src/error.rs
- Bump dependencies
- Updated and formated changelog for the rc
- Bump espflash and cargo-espflash version to `3.0.0-rc.1`
- Bump MSRV to 1.74
I've successfully finished a round of testing, where I tested:
- Flashing and monitoring
- Erasing and reading flash
- Save-image and write-bin
- Configuration file (locally and globally)
See details test and results bellow.
Used a basic `esp-template` for all targets and also an `esp-idf-tempalte` in C3 and S3
- ESP32
- `cargo espflash flash -M`
- `espflash flash -M`
- `espflash monitor`
- ESP32-S2 (UART port)
- `cargo espflash flash -M`
- `espflash flash -M`
- ESP32-S3 (UART, USB ports) - std and no_std app
- `cargo espflash flash -M`
- `espflash flash -M`
- ESP32-C2 (26MHz and 40MHz)
- `cargo espflash flash -M`
- `espflash flash -M` 
- ESP32-C3 …
> Prepare 3.0.0-rc.1 release

- CHANGELOG.md
- espflash/src/targets/flash_target/esp32.rs
- Prepare CHANGELOG for next dev-cycle
- Update log message when we skip writing a segment. Here is how it looks, reflashing an app where only the app changed:
```
...
App/part. size:    223,776/4,128,768 bytes, 5.42%
[2024-02-19T09:16:12Z INFO ] Segment at address '0x0' did not change, skipping it
[2024-02-19T09:16:12Z INFO ] Segment at address '0x8000' did not change, skipping it
[00:00:01] [========================================]      74/74      0x10000                                                                                                                                                                                    [2024-02-19T09:16:14Z INFO ] Flashing has completed!
```
- Include the removal of Cargo package metadata configuration in changelog.
cc: @jessebraham …
> Address minor feedback things of rc.1

- CHANGELOG.md
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
> Return `crate::Error` instead of a miette Report

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/connection/mod.rs
- espflash/src/connection/reset.rs
- Reuse `reset_after_flash` sequence in `hard_reset`
- We dont know where this sequence came from, but it seems to work fine in all platforms. See #157 and #153
- Using [`esptool` HardReset sequence](https://github.com/espressif/esptool/blob/3301d0ff4638d4db1760a22540dbd9d07c55ec37/esptool/reset.py#L132-L153) does not work in Windows.
- Move `reset_after_flash` method to `reset` module  
Thanks @bjoernQ for the help debugging and testing this
> Fix USB JTAG Serial HardReset sequence in Windows

- CHANGELOG.md
- cargo-espflash/README.md
- espflash/README.md
- espflash/src/cli/config.rs
- Local `espflash.toml` config file can also be stored in parent folder to simplify Cargo workspaces
> Allow Cargo workspace config file

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/error.rs
- Add `--list-all-ports` connection argument to avoid serial port filtering
- In all the targets, except for linux-musl, only list the available USB Ports by default (#590)
~~Draft PR until it can be properly tested and we verify that it closes #575~~
@jessebraham verified that it resolves #575, thanks for testing it!
> Add list-all-ports flag and filter the default list

- CHANGELOG.md
- espflash/src/cli/monitor/symbols.rs
This improves how we resolve non-code addresses.
Before
```
load:0x40080400,len:4
0x40080400 - _DoubleExceptionVector
at ??:??
ho 8 tail 4 room 4
load:0x40080404,len:3876
0x40080404 - _DoubleExceptionVector
at ??:??
entry 0x4008064c
0x4008064c - __user_exception
at C:\Users\Bjoern\.cargo\registry\src\index.crates.io-6f17d22bba15001f\esp-backtrace-0.11.0\src\lib.rs:130
```
After
```
load:0x40080400,len:4
ho 8 tail 4 room 4
load:0x40080404,len:3876
entry 0x4008064c
0x4008064c - __user_exception
at C:\Users\Bjoern\.cargo\registry\src\index.crates.io-6f17d22bba15001f\esp-backtrace-0.11.0\src\lib.rs:130
```
`__user_exception` is still confusing but at least it's the same result as `xtensa-esp32-elf-addr2line`
> Improve resolving non-code addresses

- .github/workflows/hil.yml
- Cargo.lock
- cargo-espflash/Cargo.toml
- Update `cargo-espflash` deps and `cargo update` to get [`cc>=1.0.88`](https://github.com/esp-rs/espflash/issues/597#issuecomment-1963259738) which should fix #597 
- Bump some CI actions version to avoid warnings, see https://github.com/esp-rs/espflash/actions/runs/8046179600 for example
~Draft until we confirm that #597 is solved with this dependency update.~
> Fix macOS installation

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- espflash/Cargo.toml
- Update dependencies
- Bump `espflash` and `cargo-espflash` version
- Update changelog
> Prepare 3.0.0-rc.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cargo-espflash/Cargo.toml
- espflash/Cargo.toml
- Bump `espflash` and `cargo-espflash` version
- Bump dependencies
- Format toml files
- Update changelog
~Draft until #610 is merged and proper testing is done~
I've successfully finished a round of testing, where I tested:
- Flashing and monitoring
- Erasing and reading flash
- Save-image and write-bin
See details test and results bellow.
Used a basic `esp-template` for all targets and also an `esp-idf-tempalte` in C3 and S3. `ESPFLASH_BAUD` was set to `921600`.
- ESP32
- `cargo espflash flash -M`
- `espflash flash -M`
- ESP32-S2 (UART port)
- `cargo espflash flash -M`
- `espflash flash -M`
- ESP32-S3 (UART, USB ports) - std and no_std app 
- `cargo espflash flash -M`
- `espflash flash -M`
- ESP32-C2 (26MHz and 40MHz)
- `cargo espflash flash -M`
- `espflash flash -M` 
- ESP32-C3 (UART, …
> Prepare 3.0.0 release

- .github/workflows/release.yml
- Use Ubuntu 22.04 as 20.04 leads to: https://github.com/esp-rs/espflash/actions/runs/8264223261/job/22607923609.
Successful CI run with ubuntu22.04: https://github.com/SergioGasquez/espflash/actions/runs/8264491562/job/22608213573
> Update runner for arch64 and armv7 linux jobs

- CHANGELOG.md
- espflash/src/cli/mod.rs
The size parameter of the read-flash subcommand indicated it was erasing flash.
> Fixed docs for read-flash size parameter

- CHANGELOG.md
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
This supports loading the flash size, frequency, and mode from the config file.
> Support loading flash settings from the config file

- CHANGELOG.md
- cargo-espflash/src/main.rs
The package ID format was officially documented as an opaque identifier and the only thing we were allowed to do with them is look them up in the cargo metadata.  Rust 1.77 switched the package ID field to use the publicly documented "Package ID Specification" format instead, which means that the old logic no longer works.
> Always resolve package_id from metadata when finding bootloader and partition table

- CHANGELOG.md
- espflash/src/cli/serial.rs
Hi, I've been trying to use espflash from Alpine linux and on my system `serialport::available_ports()` returns something like `[SerialPortInfo { port_name: "/dev/ttyS0", port_type: Unknown }, SerialPortInfo { port_name: "/dev/ttyUSB0", port_type: Unknown }]`. The function that handles this expects `port_name` to be in the form of `/sys/class/tty/*` and this makes espflash not work on my system due to being unable to detect any serial ports.
In this PR I've added a branch which checks if the path returned from `available_ports` starts with `/dev/` and if it does it replaces it with `/sys/class/tty/` and proceeds as before. I can confirm this works for flashing esp32c3 board I'm working with.
I'm not sure this is the best approach but at least it works now. Let me know if you think this …
> fix: musl list ports handle /dev/* from available_ports

- CHANGELOG.md
- espflash/src/image_format.rs
Perhaps I am misunderstanding what the --target-app-partition flag is supposed to do, but the code previously always wrote the image to the "factory" app partition if one was present, regardless of the partition specified with the `--target-app-partition` flag.
This change updates the code to write the image to the partition specified with the `--target-app-partition` flag.
I confirmed that using `espflash flash --target-app-partition ota_0` now causes espflash to write the image to the `ota_0` partition.  Note that this leaves the `factory` partition and any `ota_data` partition unchanged, so the bootloader will still boot from the factory partition by default, but this makes it possible to write new app images to the OTA partitions for testing purposes.
> Write the image to the correct target app partition

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- espflash/Cargo.toml
- espflash/README.md
- Update changelog
- Bump `espflash` and `cargo-espflash` version
- Update dependencies
- Bump MSRV to 1.76.0
> Version 3.1.0

- .github/actions/setup-target/action.yml
See https://github.com/esp-rs/espflash/actions/runs/9251830464. Node JS16 is getting deprecated.
> Avoid NodeJS warning

- CHANGELOG.md
- cargo-espflash/src/main.rs
Default features are still included while using the following command:
```bash
cargo espflash flash --release --features one,two
```
This PR add the `--no-default-features` flag to mirror cargo features functionalities.
Close https://github.com/esp-rs/espflash/issues/645
> feat: add --no-default-features flag

- CHANGELOG.md
- Cargo.lock
- espflash/Cargo.toml
- Downgrade crossterm to 0.25.0
- Update time to avoid build failure
> Downgrade crossterm and fix compilation

- CHANGELOG.md
- espflash/src/cli/monitor/mod.rs
> Make monitor only send key on press, not on release

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/package_metadata.rs
- espflash/Cargo.toml
- Update `bytemuck` as `1.16.0` was yanked
- Update `cargo` and update code accordingly as we now should use [`GlobalContext::default`](https://docs.rs/cargo/0.81.0/cargo/util/context/struct.GlobalContext.html) instead of  [`Config::default`](https://docs.rs/cargo/0.78.0/cargo/util/config/struct.Config.html#method.default)
> Update bytemuck dependency

- CHANGELOG.md
- espflash/src/targets/esp32p4.rs
Minor updates, nothing exciting.
Output:
```text
jesse@mbp ~/W/espflash git:feature/esp32p4 [ ✎ ⚑ ]
🦀 nightly@1.83.0 λ espflash board-info
[2024-10-07T10:36:33Z INFO ] Detected 2 serial ports
[2024-10-07T10:36:33Z INFO ] Ports which match a known common dev board are highlighted
[2024-10-07T10:36:33Z INFO ] Please select a port
[2024-10-07T10:36:34Z INFO ] Serial port: '/dev/cu.usbmodem14201'
[2024-10-07T10:36:34Z INFO ] Connecting...
[2024-10-07T10:36:34Z INFO ] Using flash stub
Chip type:         esp32p4 (revision v0.1)
Crystal frequency: 40 MHz
Flash size:        16MB
Features:          High-Performance MCU
MAC address:       60:55:f9:f9:04:5e
```
And when using `esptool.py get_security_info` (output has been truncated):
```text
jesse@mbp ~/W/espflash git:feature/esp32p4 [ ✎ ⚑ ]
🦀 …
```
> Add new chip detect magic value, ability to read chip revision for ESP32-P4

- CHANGELOG.md
- espflash/src/cli/monitor/parser/esp_defmt.rs
I found timestamp in defmt documents, but following their instruction still don't show timestamp.
Spent a week figured out it's because espflash didn't display it.
This change made following work too
in Cargo.toml dependency:
embassy-time        ={ version = "0.3.1" , features = ["defmt-timestamp-uptime"] }
> Display timestamp, useful to find timing problem

- CHANGELOG.md
- espflash/src/connection/mod.rs
Previously, this failed to detect download mode during this regex match in the following message.
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x0 (DOWNLOAD(USB/UART0))
waiting for download
```
`.*` only matches on any character EXCEPT line breaks,  where as `[\s\S]` will match on anything.
> Update download mode detection

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
Add a new global option to prevent espflash from checking updates.
It will make it work faster behind a proxy.
Closes #688
> Add skip update check option

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- espflash/Cargo.toml
These patch releases just update the dependencies and resolve the outstanding issues due to yanked dependencies. Some minor changes were merged previously, see `CHANGELOG.md` for more information.
Closes #671
> New releases

- CHANGELOG.md
- espflash/src/cli/serial.rs
Since the list of available ports were being filtered down by default, when specifying a port via CLI option or configuration file which had been filtered out, the port was reported as unavailable. This should resolve the issue by only filtering the list of ports if no port was specified.
@trombik are you able to test this branch out and confirm that it indeed resolves the issue for you, please?
Closes #692
> If a port was specified via CLI or config, search *all* serial ports, not just the filtered list

- Cargo.lock
- espflash/Cargo.toml
Notable changes/fixes:
- A fix for usb device enumeration on linux when the device is reported as pci device
- Reporting usb port information on linux without libudev
- And an overhaul for device enumeration on macos
No `CHANGELOG.md` entry required.
> Update `serialport` dependency

- CHANGELOG.md
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
Change to implement #699 
I tested this with `espflash.toml` in the local directory:
```
partition_table_offset = 0xA000
[flash]
size = "8MB"
```
It works as expected, I can see that when I change the partition_table_offset address in the config file that the tool's behavior honors that change.
> Allow `partition_table_offset` to be specified in the config file. (for #699)

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- espflash/src/command.rs
- espflash/src/connection/mod.rs
- espflash/src/connection/reset.rs
- espflash/src/elf.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/ram.rs
Subject says it all.
99% of the changes here are the result of 
```sh
rustup default nightly
cargo clippy --alllow-dirty --fix
```
... and then I added `#[allow(clippy::too_many_arguments)]` to two constructor functions as clippy complained (apparently they reduced the threshold down to 7 arguments before the complaints start)
> Make clippy happy

- CHANGELOG.md
- espflash/Cargo.toml
Subject says it all. 
The main driver for this is to be able to cross-compile `espflash` for other Linux targets (e.g. Raspberry Pi) with either:
```sh
cross build --release --target=arm-unknown-linux-gnueabihf
```
or
```sh
cargo zigbuild --target aarch64-unknown-linux-gnu.2.17
```
Neither of these can do it when the dependency to `libudev` is present, and both do succeed when the dependency to `libudev` is not there.
I'm yet to test this on a RPI (real soon), but on a regular Ubuntu 22.04, disabling the `libudev` dependency actually does not lead to a visible loss in functionality. At least not when `espflash` is driven programmatically via its API as I did.
`/dev/ttyUSB0` is still detected as _the_ serial port where the esp32(s3) device is answering.
> Make the libudev dependency optional

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/README.md
- espflash/Cargo.toml
- espflash/README.md
Opening as a draft for now, not going to merge/release until Monday.
Just bumped the dependencies, the point of this release is mostly just to get the current changes in `main` published while we begin work on the next major release. This unfortunately resulted in a pretty hefty bump in the MSRV, but I don't really feel like fighting with different versions to find some middle ground, so it is what it is.
A couple dependencies are still outdated, as we have had issues when trying to update them (`addr2line` and `crossterm`). This is something I'd like to address in v4, but again not going to bother with it right now.
> Version 3.3.0

- CHANGELOG.md
- espflash/Cargo.toml
- espflash/src/image_format.rs
The current implementation uses the last 32 bytes of the bootloader file. When Secure Boot V2 is enabled, the bootloader is padded. The new implementation walks through the segments to find the end and adds the 16-byte aligned 1-byte checksum to update the SHA256 instead of incorrectly updating the padding.
Closes #715
> Calculate end of bootloader to update SHA256

- CHANGELOG.md
- cargo-espflash/src/main.rs
https://github.com/esp-rs/espflash/pull/705#discussion_r1858239611 fixed the collision for `espflash` but not for `cargo-espflash`
> [cargo-espflash]: Fix `-s` collision

- .github/workflows/ci.yml
- .github/workflows/hil.yml
Addresses the known issues reported in https://github.com/esp-rs/espflash/issues/730
Not sure if it will avoid the cancelled HIL run, but I copied the workflow triggers from esp-hal, where it doesnt happen
> Avoid running  hil twice and add `--no-skip` to espflash flash command

- .github/actions/setup-target/action.yml
- .github/workflows/ci.yml
This has pretty drastically reduced the runtime on my fork at least. Some additional re-org in here too, sorry for the noise.
Additional considerations:
- The matrices in the `check`, `check-lib`, and `msrv` jobs are different
- Should we check all platforms/archs for each of these jobs, or is a limited subset adequate?
- If the latter, which platforms should be checked? Is x86_64 macOS/Linux/Windows enough for the `check-lib` and `msrv` jobs? Something else?
> Additional improvements to CI workflow

- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/monitor/parser/mod.rs
There has been a built-in solution for this problem in Rust for quite some time now, so no reason to depend on this package anymore.
> Remove the dependency on `lazy_static` in favour of built-in `LazyLock`

- CHANGELOG.md
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/tests/scripts/flash.sh
- Adds non-interactive to `flash`
- Creates a struct with monitoring config
- Add the `--no-reset` flag
- Use different baudrate for connecting and for monitoring
> Improve monitoring

- espflash/src/cli/serial.rs
Now that `serialport` enumerates more ports without the use of `libudev` (see https://github.com/serialport/serialport-rs/pull/238), perhaps port detection will work as expected on Linux systems using MUSL without the specialized function for these platforms.
Opening as a draft as I currently have no way to test this, if somebody from the community is able to verify port detection still works on Linux systems using MUSL that would very much be appreciated!
If things continue to work as expected, would be nice to get rid of this extra code. If not, no real loss I guess, and this PR can just be closed.
> Remove special handling of MUSL Linux now that we no longer use libudev

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/esp_defmt.rs
- espflash/src/command.rs
- espflash/tests/scripts/checksum-md5.sh
I also removed some short arguments that didnt make much sense to me (I can revert those)
> Normalize similar arguments

- CHANGELOG.md
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/README.md
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/serial.rs
This pull request uses the existing logic for finding the serial ports to to create a new 'list-ports' command that just lists the ports that are available, with some additional information. This allows for some additional information when trying to resolve issues when flashing. It also opens some opportunities for scripting, e.g. to flash multiple connected devices from a single script.
By default only the ports that are 'known', that is ports that might be automatically selected are shown. The -a (or --all-ports) flag shows all serial ports available.
Tested on Ubuntu, Windows and OS-X.
> Add a command to list available serial ports

- .github/workflows/hil.yml
Not sure this is the best way but I like it more compared to editing all scripts and wrapping them in a timeout helpers. Maybe I'm missing other simpler option. 
closes https://github.com/esp-rs/espflash/issues/774
> Add timeout to HIL tests

- CHANGELOG.md
- cargo-espflash/README.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
For some reason we were missing this command. Unless there is a reason for it, which I cant think off, we should have the same commands as in `espflash`
> [cargo-espflash]: Add write-bin subcommand

- .github/workflows/hil.yml
Part 1 of #786 
Still need to update the `release` workflow as well, but not entirely sure how to approach that yet. Can at least get HIL updated for now, though.
> Update HIL workflow to use `ubuntu-22.04`, build in container to resolve GLIBC errors

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/connection/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/flash_target/esp32.rs
Nothing major here, just some simple cleanup:
- Improve error messages when receiving an incorrect response type, avoid some unwraps
- Remove `get_` prefix from `get_usb_pid`, remove useless `Result` from return type
Still a bit of untangling to do with regards to some imports from `flasher` in the `connection` module, but it's looking mostly okay I think. Not clear to me how to resolve those yet so will deal with it another time.
> Minor error handling and function naming improvements

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/elf.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format.rs
- espflash/src/lib.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/flash_target/mod.rs
- espflash/src/targets/flash_target/ram.rs
- Eliminated the `ElfFirmwareImage` struct, as this was essentially just wrapping `xmas_elf::ElfFile`
- Merged `RomSegment` and `CodeSegment` structs into a new `Segment` struct, as they were identical
- Re-export a couple types from the `elf` module which are present in public APIs
- Removed unused `segments_with_load_addresses` function from `FirmwareImage` trait
> Refactor and simplify the `elf` module a bit

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32p4.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/mod.rs
> Don't expose `PartitionTable` struct in public APIs, simplify `IdfBootloaderFormat` constructor

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
With this PR we will update the flash size in the following order:
1. Provided by `--flash-size` arg
2. Config file 
3. Detect if we can (if we are flashing we can try to detect, but `save-image` cant)
4. Used the default flash size: 4Mb
We have to pass `flasher` arround which is not ideal... I initially though of https://github.com/esp-rs/espflash/commit/cfef334b24b1bf1bf6629272f9a6ea268f46f7a8 but that results in lots of duplicated code.
I generated an std template: `cargo generate esp-rs/esp-idf-template cargo` for S3 and with the default configurations. Updated the code to:
```rust
// Define a large static array (roughly 1MB)
// 1MB = 1 * 1024 * 1024 bytes
static LARGE_ARRAY: [u8; 1 * 1024 * 1024] = [0; 1 * 1024 * 1024];
fn main() {
// It is necessary to call this function once. …
```
> Update flash size 

- Cargo.lock
- cargo-espflash/Cargo.toml
This resolves the error when using `edition = "2024"` in a package, see #799 for more details.
> Update `cargo` dependency in `cargo-espflash`

- CHANGELOG.md
- Cargo.lock
- cargo-espflash/src/main.rs
- espflash/Cargo.toml
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/connection/mod.rs
- espflash/src/connection/reset.rs
- espflash/src/flasher/mod.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32p4.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/flash_target/esp32.rs
- espflash/src/targets/mod.rs
This is mostly experimental, so opening as a draft. 
I've been playing with (cc cc https://github.com/esp-rs/espflash/issues/691)  and I was able to reproduce the issue with espflash AND esptool as well, following the same steps as mentioned [here](https://github.com/esp-rs/espflash/issues/556#issuecomment-1921143340)
I looked into esptool and specifically to [this commit](https://github.com/espressif/esptool/commit/8298cdcc68a8063df1ca932d42e21555e15269b3#diff-24560e81a6dac1814c9801703e7c13e2983585356da84fedc207ac9437c42dab). `esptool` not using this fix as default for SERIAL_JTAG, it can be used manually with: 
`--after reset_watchdog`
The reasons (from esptool perspective) it's not on by default are: 
1. The RTC WDT hack is not available on all devices (e.g., the H2 doesn't have it). …
> Implement new USB Serial JTAG reset strategy

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
Nothing of interest here, just some cleanup:
- Removed a couple unused dependencies from `cargo-espflash`
- Noticed that both binaries contained two identical functions, so pulled them into the `cli` module
> Remove unused dependencies, deduplicate some functions

- CHANGELOG.md
- espflash/src/connection/mod.rs
Closes https://github.com/esp-rs/espflash/issues/656
```
cargo run --bin espflash board-info                                                                       
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.64s
Running `target\debug\espflash.exe board-info`
[2025-03-24T14:50:24Z INFO ] Serial port: 'COM57'
[2025-03-24T14:50:24Z INFO ] Connecting...
[2025-03-24T14:50:24Z INFO ] Using flash stub
Chip type:         esp32s2 (revision v1.0)
Crystal frequency: 40 MHz
Flash size:        8MB
Features:          WiFi, No Embedded Flash, Embedded PSRAM 2MB, ADC and temperature sensor calibration in BLK2 of efuse V2
MAC address:       70:04:1d:fa:00:c4
Security Information:
=====================
Flags: 0x00000000 (0)
Key Purposes: [0, 0, 0, 0, 0, 0, 0]
Secure Boot: Disabled
Flash …
```
> Fix connecting to S2 over USB

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/esp_defmt.rs
The formatting options are identical to probe-rs's, except in espflash we can't control timestamp/location with switches. The user can supply a custom format string if such control is necessary.
Closes #520 
Closes #781
> Option to supply custom defmt formats

- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/config.rs
- espflash/src/image_format/esp_idf.rs
- Removed the dependency on the `hex` package
- Renamed (de)serialization functions (just thought they could be a bit more clear, internal-only anyway)
> Remove the dependency on `hex`

- Cargo.lock
- espflash/Cargo.toml
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/esp_idf.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32p4.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/mod.rs
While these changes _technically_ have user-facing effects, we need to remove `ElfFile` from the public API anyway so I will not add a `CHANGELOG.md` entry here, since it will just be obsolete once #803 is resolved anyway.
> Remove the dependency on `xmas_elf`

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/symbols.rs
- espflash/src/error.rs
- espflash/src/image_format/metadata.rs
- espflash/src/image_format/mod.rs
This PR reads chip name from the .elf and prevents flashing if it differs from the detected device.
> Check chip using metadata

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/tests/scripts/write-bin.sh
Closes #631
This PR allows specifying a partition label for `write-bin`, in addition to a numeric address. If a partition label is passed, espflash tries to parse the provided/configured partition table, and resolve the label. This information is then used to a) check the size of the flashed binary and b) specify the address where the binary should be written.
As an alternative approach, we might read back the partition table from the device itself. Since users have the option to configure a partition table in a config file, this option would need a `--read-idf-partition-table-from-device` or similar flag, meaning it can still be implemented without breaking the command's current behaviour.
> Allow flashing binary to a named partition

- CHANGELOG.md
- espflash/src/image_format/esp_idf.rs
- espflash/src/image_format/mod.rs
Fixes #552 - the problem is that the reproducer elf has 2-byte aligned segments (functions in IRAM), and espflash used to 4-byte align segment lengths prematurely, causing them to overlap. This overlap then prevented merging segments, and the end result was an elf that the bootloader was not able to load.
The firmware seems to require some propriatery, or at least project-specific data to be present, so the firmware immediately panics, but it can boot with this PR.
> Align segment lengths after merging

- CHANGELOG.md
- espflash/src/cli/mod.rs
- espflash/src/connection/mod.rs
- espflash/src/flasher/mod.rs
Some progress towards https://github.com/esp-rs/espflash/issues/726
Initial issue contains just a little bit of lie: espflash didn't work with SDM almost at all 😅
After this is merged, at least board-info command will be supported. `write-bin` support will be added later in https://github.com/esp-rs/espflash/pull/832
No extra flags are needed, user will be able to just execute:
```bash
espflash board-info
```
Also, --no-stub is applied automatically when tool detects that connected chip is in SDM mode.
> Add `board-info` command support in Secure Download Mode

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
Still far from ideal, but I guess its better than what we currently have. We will print a warning if we set any monitor arg but we dont use the monitor flag.
Also, when using `flash` subcommand the elf file is not taken from the `--elf` arg as we already know the elf. The user could still use the `--elf` flag though...
> Check monitor args

- Cargo.lock
- cargo-espflash/Cargo.toml
- cargo-espflash/src/error.rs
- cargo-espflash/src/package_metadata.rs
Still needs more testing, but this PR removes the dependency on `cargo` from the `cargo-espflash` package. This dependency has caused issues a number of times, and it quite enormous, so glad to see it gone.
Based on some very limited testing this is still working the same as it did prior to the changes, but I would like to try it out in some more interesting situations to be sure I haven't subtly broken anything.
There are no user-facing changes here, so skipping the `CHANGELOG.md` entry.
> Remove the dependency on `cargo` from the `cargo-espflash` package

- .github/actions/setup-target/action.yml
Not sure why this is suddenly required (CI worked fine yesterday), but easy fix at least 🤷🏻‍♂️
> Fix CI error by installing newly required dependency

- espflash/src/flasher/mod.rs
This took me hours of debugging when updating from espflash 2 to espflash 3. I finally figured it out by comparing my code with the espflash CLI binary's code in detail.
> Flasher: document baud rate requirement

- espflash/src/targets/efuse/esp32c2.rs
- espflash/src/targets/efuse/esp32c3.rs
- espflash/src/targets/efuse/esp32c6.rs
- espflash/src/targets/efuse/esp32h2.rs
- espflash/src/targets/efuse/esp32p4.rs
- espflash/src/targets/efuse/esp32s2.rs
- espflash/src/targets/efuse/esp32s3.rs
- xtask/src/main.rs
Oops 😅 
(Because of how we're reading the MAC address, this thankfully didn't affect `espflash`, however when porting this functionality over to `esp-hal` I noticed this change was required, so may as well be correct here anyway)
> Correct bit start offset for `MAC1` field

- CHANGELOG.md
- espflash/src/cli/mod.rs
`espflash board-info` looks like the only way to currently reset a board non-interactively, so let's make sure the advertised `-a` options are actually effective.
> Fix resetting after board-info, read_flash and checksum_md5

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/error.rs
- espflash/src/image_format/esp_idf.rs
- espflash/src/image_format/mod.rs
- espflash/src/lib.rs
This checks, if the bootloader has an app desc present, if not, returns an error. 
Also added an option for users to disable the check.
closes https://github.com/esp-rs/espflash/issues/866
> Check if bootloader has app descriptor

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/esp_idf.rs
- espflash/src/image_format/mod.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c3.rs
- espflash/src/targets/esp32c5.rs
- espflash/src/targets/esp32c6.rs
- espflash/src/targets/esp32h2.rs
- espflash/src/targets/esp32p4.rs
- espflash/src/targets/esp32s2.rs
- espflash/src/targets/esp32s3.rs
- espflash/src/targets/mod.rs
- espflash/tests/scripts/write-bin.sh
Draft PR as there are still some missing parts:
- There are still some esp-idf specifics that are not in the esp-idf module, maybe we should move them
- Not sure if I like the `make_...` methods, but I cant think of anything better
- Not sure if some things should live in `targets/<chip>.rs` or as method of the Chip enum
- This can/should be done in a later PR if required.
Any feedback or suggestion is more than welcome!
> Refactor image format

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/connection/mod.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/esp_idf.rs
- espflash/src/targets/esp32.rs
- espflash/src/targets/esp32c2.rs
- espflash/src/targets/esp32c5.rs
This PR implements the first suggestion from https://github.com/esp-rs/espflash/issues/854#issuecomment-2903849411 and enables the creation of a `Connection` outside of `Flasher::connect`.
In general this PR tries to keep the `Connection` specific things, like `sync`ing, baud rate control, reset etc in `Connection` and the flasher related things, like querying spi params, loading the flasher stub etc in `Flasher`.
> Move construction of Connection outside of flasher

- espflash/src/error.rs
- espflash/src/image_format/idf.rs
Note: For testing non-esp-hal based project, I used ESP-IDF's hello_world example, and I hope it is valid test.
closes https://github.com/esp-rs/espflash/issues/886
> Check `app_desc` _only_ for esp-hal projects

- CHANGELOG.md
- espflash/src/flasher/mod.rs
- espflash/src/flasher/stubs.rs
- espflash/src/target/efuse/esp32.rs
- espflash/src/target/efuse/esp32c2.rs
- espflash/src/target/efuse/esp32c3.rs
- espflash/src/target/efuse/esp32c5.rs
- espflash/src/target/efuse/esp32c6.rs
- espflash/src/target/efuse/esp32h2.rs
- espflash/src/target/efuse/esp32p4.rs
- espflash/src/target/efuse/esp32s2.rs
- espflash/src/target/efuse/esp32s3.rs
- espflash/src/target/efuse/mod.rs
- espflash/src/target/flash_target/esp32.rs
- espflash/src/target/flash_target/mod.rs
- espflash/src/target/flash_target/ram.rs
- espflash/src/target/mod.rs
- xtask/src/main.rs
Major change here is making the eFuse field definitions public. There was a minor change for the P4 which required some updates to read the version correctly again.
Also removed unnecessary parameters/Result types from a couple functions which do not require them.
> Make eFuse field definitions public, minor public API cleanup

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/config.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/monitor/parser/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/command.rs
- espflash/src/connection/mod.rs
- espflash/src/error.rs
- espflash/src/flasher/mod.rs
- espflash/src/image_format/idf.rs
- espflash/src/target/flash_target/esp32.rs
- espflash/src/target/flash_target/mod.rs
- espflash/src/target/flash_target/ram.rs
- espflash/src/target/mod.rs
- xtask/src/main.rs
The progress callbacks get initialized and updated even if we skip a segment. For verification, we add an extra step to the progress which is updated once verification is complete.
> Show progress when skipping and verifying

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/cli/monitor/mod.rs
- espflash/src/cli/serial.rs
- espflash/src/error.rs
Moved the `non-interactive` flag to `ConnectArgs` so we also avoid asking the user to select a port. The logic added is the following: When using `non-interactive`, it will use any of the selected ports (via flag, environment variable or config file) and if no port was selected it will: Detect the number of ports, if there is only one, it will use this one, if there are multiple ports it will throw an error (MacOs usually duplicates ports so its not ideal, maybe we should error if >2 on macos?)
> Move non-interactive flag to connect args

- CHANGELOG.md
- cargo-espflash/src/main.rs
- espflash/src/bin/espflash.rs
- espflash/src/cli/mod.rs
- espflash/src/image_format/idf.rs
- Add app descriptor check to save image
- ~~Rename `check_idf_bootloader` to `check_app_descriptor`~~
- Only check_app_descriptor for `EspIdf` format (useless for now as its the only supported, but...)
- `ImageArgs::check_app_descriptor` is now a `bool`, as it already has a default value
> Add app descriptor check to save image

- cargo-espflash/README.md
- espflash/README.md
- espflash/src/cli/config.rs
- espflash/src/error.rs
The image format refactor introduced some layers to `ProjectConfig` struct so it needs some additional parsing/checking so `espflash.toml` doesn't ignore it's options.
Closes https://github.com/esp-rs/espflash/issues/929
> Fix using `cli::IdfFormatArgs` in `espflash.toml`
